#!/bin/bash
# Anaconda env setup
 
display_usage() { 
   echo
   echo "  Auto-Config: Installing Mamba"
   echo "  ********************************"
   echo
   echo "  usage: ${0##*/} -p path_to_install_anaconda [-m]  "
   echo
   echo "  flags:  -p  full path to where anaconda will be installed"
   echo "         [-m] miniconda will be installed instead of anaconda"
   echo
   exit 1
	} 

# set miniconda to False
        mini=0
# if less than three arguments supplied, display usage 
	if [  $# -le 1 ] 
	then 
		display_usage
		exit 1
	fi 
# if less than two arguments supplied, display usage 
	if [  $# -ge 4 ] 
	then 
		display_usage
		exit 1
	fi 

while getopts :mp: option
  do
  case "${option}"
  in
  p) export INSTALL_DIR=${OPTARG};;
  m) mini=1;;
  esac
done

if [ ${INSTALL_DIR:0:1} != "/" ]; then
  echo "PREFIX must use full path"
  exit 1
fi

OS="`uname`"

case $OS in
  'Linux')
    OS='Linux'
    if [ $mini == 1 ]
    then
	    'minimamba not yet configured'
    else
	    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
	    bash Mambaforge-$(uname)-$(uname -m).sh
    fi
    ;;
  'Darwin') 
    OS='MacOSX'
    if [ $mini == 1 ]
    then
	    'minimamba not yet configured'
    else
	    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(OS)-$(uname -m).sh" 
	    bash Mambaforge-$(OS)-$(uname -m).sh
    fi
    ;;
  *) 
    echo miniforge for $OS is not available
    exit 1
    ;;
esac

conda update conda

