name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - mamba==0.24.0
  - conda==4.13.0
  - pip
  - pyproj
  - ca-certificates
  - certifi
  - openssl
  - ipykernel
  - pooch
  - spyder-kernels
  - jupyter_contrib_nbextensions
